---
title: "Chapter 1 - notes"
author: "John Peach"
date: "3/14/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```
```{r}
text <- c("Because I could not stop for Death .",
          "He kindly stopped for me .",
          "The Carriage held but just Ourselves -",
          "and Immortality")

library(dplyr)

text_df <- data.frame(line = 1:4, text = text)

library(tidytext)

text_df %>% 
  unnest_tokens(word, text)
```

```{r}
library(janeaustenr)
library(dplyr)
library(stringr)

original_books <- austen_books() %>% 
  group_by(book) %>% 
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                            ignore_case = TRUE)))) %>% 
  ungroup()

original_books
```

```{r}
library(tidytext)
tidy_books <- original_books %>% 
  unnest_tokens(word, text)

tidy_books
```

```{r}
data("stop_words")

tidy_books <- tidy_books %>% 
  anti_join(stop_words)
```

```{r}
tidy_books %>% 
  count(word, sort = TRUE)
```

```{r}
library(ggplot2)
tidy_books %>% 
  count(word, sort = TRUE) %>% 
  dplyr::filter(n > 600) %>% 
  ggplot(aes(word, n)) +
    geom_col() +
    xlab(NULL) +
    coord_flip()
```

```{r}
library(gutenbergr)
hgwells <- gutenberg_download(c(35, 36, 5230, 159))

tidy_hgwells <- hgwells %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words)

tidy_hgwells %>% 
  count(word, sort = TRUE)
```
```{r}
bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))

tidy_bronte <- bronte %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words)

tidy_bronte %>% 
  count(word, sort = TRUE)
```
```{r}
library(tidyr)
frequency <- bind_rows(mutate(tidy_bronte, author = "Bronte Sisters"),
                       mutate(tidy_hgwells, author = "H. G. Wells"),
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>% 
  count(author, word) %>% 
  group_by(author) %>% 
  mutate(proprotion = n / sum(n)) %>% 
  select(-n) %>% 
  spread(author, proprotion) %>% 
  gather(author, proportion, `Bronte Sisters`:`H. G. Wells`)
```
```{r}
library(ggplot2)
library(scales)
ggplot(frequency, aes(x = proportion, y = `Jane Austen`,
  colour = abs(`Jane Austen` - proportion))) +
  geom_abline(colour = 'gray40', lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  scale_color_gradient(limits = c(0, 0.001),
                       low = 'darkslategray4', high = 'gray75') +
  facet_wrap(~author, ncol = 2) +
  theme(legend.position = 'none') +
  labs(y = "Jane Austen", x = NULL)
```
```{r}
cor.test(data = frequency[frequency$author == "Bronte Sisters", ],
         ~ proportion + `Jane Austen`)
```

```{r}
cor.test(data = frequency[frequency$author == "H. G. Wells", ],
         ~ proportion + `Jane Austen`)
```
