---
title: "Chapter 2 - notes"
author: "John Peach"
date: "3/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```


```{r }
library(tidytext)

sentiments
```
```{r}
library(textdata)
get_sentiments('afinn')
get_sentiments('bing')
get_sentiments('nrc')
```

```{r}
library(janeaustenr)
library(dplyr)
library(stringr)

tidy_books <- austen_books() %>% 
  group_by(book) %>% 
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                 ignore_case=TRUE)))) %>% 
  ungroup() %>% 
  unnest_tokens(word, text)
# unnest mapped '&' to 'and'
```

```{r}
nrcjoy <- get_sentiments('nrc') %>% 
  dplyr::filter(sentiment == 'joy')

tidy_books %>% 
  dplyr::filter(book == 'Emma') %>% 
  dplyr::inner_join(nrcjoy) %>% 
  count(word, sort = TRUE)
```

```{r}
library(tidyr)
janeaustensentiment <- tidy_books %>% 
  inner_join(get_sentiments('bing')) %>% 
  count(book, index = linenumber %/% 80, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative)
```

```{r}
library(ggplot2)
ggplot(janeaustensentiment, aes(index, sentiment, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = 'free_x')
```
```{r}
pride_prejudice <- tidy_books %>% 
  dplyr::filter(book == 'Pride & Prejudice')

pride_prejudice
```
```{r}
afinn <- pride_prejudice %>% 
  inner_join(get_sentiments('afinn')) %>% 
  group_by(index = linenumber %/% 80) %>% 
  rename(score = value) %>%  # I had to add this in
  summarise(sentiment = sum(score)) %>% 
  mutate(method = "AFINN")

bing_and_nrc <- bind_rows(
  pride_prejudice %>% 
    inner_join(get_sentiments('bing')) %>% 
    group_by(index = linenumber %/% 80) %>% 
    mutate(method = "Bing et al."),
  pride_prejudice %>% 
    inner_join(get_sentiments('nrc') %>% 
                dplyr::filter(sentiment %in% c('positive', 'negative'))) %>% 
    mutate(method = 'NRC')) %>% 
  count(method, index = linenumber %/% 80, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative)
```
```{r}
bind_rows(afinn, bing_and_nrc) %>% 
  ggplot(aes(index, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = 'free_y')
```

```{r}
get_sentiments('nrc') %>% 
  dplyr::filter(sentiment %in% c('positive', 'negative')) %>% 
  count(sentiment)
```

```{r}
get_sentiments('bing') %>% 
  dplyr::filter(sentiment %in% c('positive', 'negative')) %>% 
  count(sentiment)
```
```{r}
bing_word_counts <- tidy_books %>% 
  inner_join(get_sentiments('bing')) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  ungroup()

bing_word_counts
```
```{r}

bing_word_counts %>% 
  group_by(sentiment) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n, fill = sentiment)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(~sentiment, scales = 'free_y') +
    labs(y = 'Contribution to sentiment', x = NULL) +
    coord_flip()
```

```{r}
custom_stop_words <- bind_rows(data_frame(word = c('miss'),
                                          lexicon = c('custom')),
                               stop_words)
```
```{r}
library(wordcloud)
tidy_books %>% 
  anti_join(stop_words) %>% 
  count(word) %>% 
  with(wordcloud(word, n, max.words = 100))
```
```{r}
library(reshape2)
tidy_books %>% 
  inner_join(get_sentiments('bing')) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  acast(word ~ sentiment, value.var = 'n', fill = 0) %>% 
  comparison.cloud(colors = c('gray20', 'gray80'), max.words = 100)
```
```{r}
PandP_sentences <- data_frame(text = prideprejudice) %>% 
  unnest_tokens(sentence, text, token = 'sentences')

PandP_sentences$sentence[2]
```

```{r}
austen_chapters <- austen_books() %>% 
  group_by(book) %>% 
  unnest_tokens(chapter, text, token = 'regex', 
                pattern = "Chapter|CHAPTER [\\dIVXLC]") %>% 
  ungroup()

austen_chapters %>% 
  group_by(book) %>% 
  summarise(chapters = n())
```

```{r}
bingnegative <- get_sentiments('bing') %>% 
  dplyr::filter(sentiment == 'negative')

wordcounts <- tidy_books %>% 
  group_by(book, chapter) %>% 
  summarize(words = n())

wordcounts <- tidy_books %>% 
  semi_join(bingnegative) %>% 
  group_by(book, chapter) %>% 
  summarise(negativewords = n()) %>% 
  left_join(wordcounts, by = c('book', 'chapter')) %>% 
  mutate(ratio = negativewords / words) %>% 
  dplyr::filter(chapter != 0) %>% 
  top_n(1) %>% 
  ungroup()

wordcounts
```

